---
services:
  ts-op-connect:
    image: tailscale/tailscale:latest
    container_name: ts-op-connect
    hostname: ${TAILSCALE_HOSTNAME}
    networks:
      - op-connect
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  op-connect-api:
    bulid: connect-api
    volumes:
      - "data:/home/opuser/.op/data"
    network_mode: service:ts-op-connect

  op-connect-sync:
    bulid: connect-sync
    volumes:
      - "data:/home/opuser/.op/data"
    networks:
      - op-connect
    restart: unless-stopped

volumes:
  data:
  tailscale:

networks:
  op-connect:
